### ISSUE TITLE
[FEATURE] View 에 새로운 영역 만들기

### ISSUE THREAD

**Issue by dn7638** [CAU-OSS-project-practice/file-manager#6]
## 📝  To-do

- [ ] View : tree 부분에 데이터 정보 수정 (column 추가)
- [ ] update file : update file 함수의 결과로 만들어지는 file_list, dir_list에 들어가는 인자중 git status를 나타낼 이미지를 보여줄 인자 추가
- [ ] 임시 이미지 추가

## 📆 Date

23.05.04 ~ 23.05.06
