### ISSUE TITLE
[FEATURE] 버튼에 git add 기능 구현해서 status 값 변경하기

### ISSUE THREAD

**Issue by rbgksqkr** [CAU-OSS-project-practice/file-manager#9]
## 📝  To-do

- [ ] git add 함수 동작 확인
- [ ] 버튼이랑 이벤트 연결하기
- [ ] add했을 때 status 값 변경하기
## 📆 Date

22.05.06 ~ 22.05.07
